In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data1=pd.read_csv("DataBM.csv", sep=";")
data1 = data1.rename(columns={"Année": "Années"})
data1.head()

,Années,Pays,Code_Pays,Statut,LE_hommes,LE_femmes,LE_60_femmes,LE_60_hommes,Mort_inf_filles,Mort_inf_garçons,...,Pop_65_69_hommes,Pop_70_74_femmes,Pop_70_74_hommes,Pop_75_79_femmes,Pop_75_79_hommes,Pop_80_plus_femmes,Pop_80_plus_hommes,LE_WMGap,LE_WMGap_60,DPGS(%DCS)
0,2000,Afrique du Sud,ZAF,Developing,55.415,61.082,18.9311,16.1083,43.1,50.5,...,1.537589,1.525757,1.107638,0.889006,0.661806,0.881770,0.599231,5.667,2.8228,36.594543
1,2001,Afrique du Sud,ZAF,Developing,54.583,59.491,18.6864,16.0578,43.9,51.2,...,1.477294,1.619396,1.151636,0.908636,0.666223,0.916061,0.621060,4.908,2.6286,33.733162
2,2002,Afrique du Sud,ZAF,Developing,53.215,57.703,18.7287,15.9335,44.3,51.5,...,1.425694,1.698456,1.181962,0.945997,0.679119,0.945302,0.637910,4.488,2.7952,34.528141
3,2003,Afrique du Sud,ZAF,Developing,51.993,56.266,18.6059,15.6566,45.0,52.1,...,1.394812,1.755738,1.191550,1.001445,0.700578,0.968578,0.650782,4.273,2.9493,39.636044
4,2004,Afrique du Sud,ZAF,Developing,51.915,55.754,19.0619,15.9451,45.3,52.3,...,1.393029,1.782337,1.175094,1.072526,0.729919,0.990046,0.660463,3.839,3.1168,39.368675

In [3]:
data1["Pays"].unique()

array(['Afrique du Sud', 'Allemagne', 'Brésil', 'Canada', 'Chili',
       'Chine', 'Corée du Sud', "Côte d'Ivoire", 'Espagne', 'France',
       'Inde', 'Indonésie', 'Iran', 'Japon', 'Maroc', 'Mexique',
       'Nigeria', 'Pérou', 'Royaume-Uni', 'Russie', 'Suisse', 'Suède',
       'Sénégal', 'Togo', 'Turquie', 'États-Unis'], dtype=object)

In [4]:
data1.shape

(572, 52)

In [5]:
data2 = pd.read_csv("DataCancerfinal.csv", sep=';')
data2.head()

,Années,Pays,Cancer_thyroïde,Cancer_Estomac,Cancer_Utérus,Cancer_Foie,Cancer_Sein,Cancer_Testicule,VIH/SIDA
0,2000,Afrique du Sud,6.693356,131.697408,15.423897,131.770679,176.759697,5.076181,21126.732715
1,2001,Afrique du Sud,6.608833,127.524049,15.438783,129.330777,172.018849,4.962910,24856.531168
2,2002,Afrique du Sud,6.539335,124.374873,15.400269,127.492964,170.407084,4.924796,28413.659156
3,2003,Afrique du Sud,6.551281,121.638201,15.357450,124.881330,170.711113,4.941108,31314.350156
4,2004,Afrique du Sud,6.393602,115.205262,15.116203,119.238627,170.457759,4.780689,33291.515421

In [6]:
data2["Pays"].unique()

array(['Afrique du Sud', 'Allemagne', 'Brésil', 'Canada', 'Chili',
       'Corée du Sud', 'Côte d’Ivoire', 'Espagne', 'France', 'Inde',
       'Indonésie', 'Iran', 'Japon', 'La Chine', 'Maroc', 'Mexique',
       'Nigeria', 'Pérou', 'Royaume-Uni', 'Russie', 'Suisse', 'Suède',
       'Sénégal', 'Togo', 'Turquie', 'États Unis'], dtype=object)

In [7]:
data2.shape

(572, 9)

In [8]:
print(data1.columns)
print(data2.columns)

Index(['Années', 'Pays', 'Code_Pays', 'Statut', 'LE_hommes', 'LE_femmes',
       'LE_60_femmes', 'LE_60_hommes', 'Mort_inf_filles', 'Mort_inf_garçons',
       'PIB_habitant', 'Gini', 'Mort_adultes_hommes', 'Mort_adultes_femmes',
       'Dep_sante_PIB', 'Pop_0_4_filles', 'Pop_0_4_garçons', 'Pop_5_9_filles',
       'Pop_5_9_garçons', 'Pop_10_14_filles', 'Pop_10_14_garçons',
       'Pop_15_19_filles', 'Pop_15_19_garçons', 'Pop_20_24_femmes',
       'Pop_20_24_hommes', 'Pop_25_29_femmes', 'Pop_25_29_hommes',
       'Pop_30_34_femmes', 'Pop_30_34_hommes', 'Pop_35_39_femmes',
       'Pop_35_39_hommes', 'Pop_40_44_femmes', 'Pop_40_44_hommes',
       'Pop_45_49_femmes', 'Pop_45_49_hommes', 'Pop_50_54_femmes',
       'Pop_50_54_hommes', 'Pop_55_59_femmes', 'Pop_55_59_hommes',
       'Pop_60_64_femmes', 'Pop_60_64_hommes', 'Pop_65_69_femmes',
       'Pop_65_69_hommes', 'Pop_70_74_femmes', 'Pop_70_74_hommes',
       'Pop_75_79_femmes', 'Pop_75_79_hommes', 'Pop_80_plus_femmes',
       'Pop_80_plus_hommes', 'LE_WMGap', 'LE_WMGap_60', 'DPGS(%DCS)'],
      dtype='object')
Index(['Années', 'Pays', 'Cancer_thyroïde', 'Cancer_Estomac', 'Cancer_Utérus',
       'Cancer_Foie', 'Cancer_Sein', 'Cancer_Testicule', 'VIH/SIDA'],
      dtype='object')

In [9]:
datafusion = data1.merge(data2, on=["Années", "Pays"], how="inner")
datafusion.head()

,Années,Pays,Code_Pays,Statut,LE_hommes,LE_femmes,LE_60_femmes,LE_60_hommes,Mort_inf_filles,Mort_inf_garçons,...,LE_WMGap,LE_WMGap_60,DPGS(%DCS),Cancer_thyroïde,Cancer_Estomac,Cancer_Utérus,Cancer_Foie,Cancer_Sein,Cancer_Testicule,VIH/SIDA
0,2000,Afrique du Sud,ZAF,Developing,55.415,61.082,18.9311,16.1083,43.1,50.5,...,5.667,2.8228,36.594543,6.693356,131.697408,15.423897,131.770679,176.759697,5.076181,21126.732715
1,2001,Afrique du Sud,ZAF,Developing,54.583,59.491,18.6864,16.0578,43.9,51.2,...,4.908,2.6286,33.733162,6.608833,127.524049,15.438783,129.330777,172.018849,4.962910,24856.531168
2,2002,Afrique du Sud,ZAF,Developing,53.215,57.703,18.7287,15.9335,44.3,51.5,...,4.488,2.7952,34.528141,6.539335,124.374873,15.400269,127.492964,170.407084,4.924796,28413.659156
3,2003,Afrique du Sud,ZAF,Developing,51.993,56.266,18.6059,15.6566,45.0,52.1,...,4.273,2.9493,39.636044,6.551281,121.638201,15.357450,124.881330,170.711113,4.941108,31314.350156
4,2004,Afrique du Sud,ZAF,Developing,51.915,55.754,19.0619,15.9451,45.3,52.3,...,3.839,3.1168,39.368675,6.393602,115.205262,15.116203,119.238627,170.457759,4.780689,33291.515421

In [10]:
datafusion["Pays"].unique()

array(['Afrique du Sud', 'Allemagne', 'Brésil', 'Canada', 'Chili',
       'Corée du Sud', 'Espagne', 'France', 'Inde', 'Indonésie', 'Iran',
       'Japon', 'Maroc', 'Mexique', 'Nigeria', 'Pérou', 'Royaume-Uni',
       'Russie', 'Suisse', 'Suède', 'Sénégal', 'Togo', 'Turquie'],
      dtype=object)

In [11]:
datafusion.columns

Index(['Années', 'Pays', 'Code_Pays', 'Statut', 'LE_hommes', 'LE_femmes',
       'LE_60_femmes', 'LE_60_hommes', 'Mort_inf_filles', 'Mort_inf_garçons',
       'PIB_habitant', 'Gini', 'Mort_adultes_hommes', 'Mort_adultes_femmes',
       'Dep_sante_PIB', 'Pop_0_4_filles', 'Pop_0_4_garçons', 'Pop_5_9_filles',
       'Pop_5_9_garçons', 'Pop_10_14_filles', 'Pop_10_14_garçons',
       'Pop_15_19_filles', 'Pop_15_19_garçons', 'Pop_20_24_femmes',
       'Pop_20_24_hommes', 'Pop_25_29_femmes', 'Pop_25_29_hommes',
       'Pop_30_34_femmes', 'Pop_30_34_hommes', 'Pop_35_39_femmes',
       'Pop_35_39_hommes', 'Pop_40_44_femmes', 'Pop_40_44_hommes',
       'Pop_45_49_femmes', 'Pop_45_49_hommes', 'Pop_50_54_femmes',
       'Pop_50_54_hommes', 'Pop_55_59_femmes', 'Pop_55_59_hommes',
       'Pop_60_64_femmes', 'Pop_60_64_hommes', 'Pop_65_69_femmes',
       'Pop_65_69_hommes', 'Pop_70_74_femmes', 'Pop_70_74_hommes',
       'Pop_75_79_femmes', 'Pop_75_79_hommes', 'Pop_80_plus_femmes',
       'Pop_80_plus_hommes', 'LE_WMGap', 'LE_WMGap_60', 'DPGS(%DCS)',
       'Cancer_thyroïde', 'Cancer_Estomac', 'Cancer_Utérus', 'Cancer_Foie',
       'Cancer_Sein', 'Cancer_Testicule', 'VIH/SIDA'],
      dtype='object')

In [12]:
datafusion.isnull().sum()

Années                 0
Pays                   0
Code_Pays              0
Statut                 0
LE_hommes              0
LE_femmes              0
LE_60_femmes           0
LE_60_hommes           0
Mort_inf_filles        0
Mort_inf_garçons       0
PIB_habitant           0
Gini                   0
Mort_adultes_hommes    0
Mort_adultes_femmes    0
Dep_sante_PIB          0
Pop_0_4_filles         0
Pop_0_4_garçons        0
Pop_5_9_filles         0
Pop_5_9_garçons        0
Pop_10_14_filles       0
Pop_10_14_garçons      0
Pop_15_19_filles       0
Pop_15_19_garçons      0
Pop_20_24_femmes       0
Pop_20_24_hommes       0
Pop_25_29_femmes       0
Pop_25_29_hommes       0
Pop_30_34_femmes       0
Pop_30_34_hommes       0
Pop_35_39_femmes       0
Pop_35_39_hommes       0
Pop_40_44_femmes       0
Pop_40_44_hommes       0
Pop_45_49_femmes       0
Pop_45_49_hommes       0
Pop_50_54_femmes       0
Pop_50_54_hommes       0
Pop_55_59_femmes       0
Pop_55_59_hommes       0
Pop_60_64_femmes       0
Pop_60_64_hommes       0
Pop_65_69_femmes       0
Pop_65_69_hommes       0
Pop_70_74_femmes       0
Pop_70_74_hommes       0
Pop_75_79_femmes       0
Pop_75_79_hommes       0
Pop_80_plus_femmes     0
Pop_80_plus_hommes     0
LE_WMGap               0
LE_WMGap_60            0
DPGS(%DCS)             0
Cancer_thyroïde        0
Cancer_Estomac         0
Cancer_Utérus          0
Cancer_Foie            0
Cancer_Sein            0
Cancer_Testicule       0
VIH/SIDA               0
dtype: int64

In [13]:
datafusion.to_csv("DatasansHALE.csv",index=False, sep=';')

In [14]:
datafusion.shape

(506, 59)

In [15]:
set(data1["Pays"]) - set(data2["Pays"])

{'Chine', "Côte d'Ivoire", 'États-Unis'}

In [16]:
data1["Pays"].unique()

array(['Afrique du Sud', 'Allemagne', 'Brésil', 'Canada', 'Chili',
       'Chine', 'Corée du Sud', "Côte d'Ivoire", 'Espagne', 'France',
       'Inde', 'Indonésie', 'Iran', 'Japon', 'Maroc', 'Mexique',
       'Nigeria', 'Pérou', 'Royaume-Uni', 'Russie', 'Suisse', 'Suède',
       'Sénégal', 'Togo', 'Turquie', 'États-Unis'], dtype=object)

In [17]:
data2["Pays"].unique()

array(['Afrique du Sud', 'Allemagne', 'Brésil', 'Canada', 'Chili',
       'Corée du Sud', 'Côte d’Ivoire', 'Espagne', 'France', 'Inde',
       'Indonésie', 'Iran', 'Japon', 'La Chine', 'Maroc', 'Mexique',
       'Nigeria', 'Pérou', 'Royaume-Uni', 'Russie', 'Suisse', 'Suède',
       'Sénégal', 'Togo', 'Turquie', 'États Unis'], dtype=object)

In [18]:
pays = {
    "La Chine": "Chine",
    "Côte d’Ivoire": "Côte d'Ivoire",   # ’ devient '
    "États Unis": "États-Unis"          # sans tiret → avec tiret
}

In [19]:
data2["Pays"] = data2["Pays"].replace(pays)

In [20]:
datafusion = data1.merge(data2, on=["Années", "Pays"], how="inner")

In [21]:
datafusion.shape

(572, 59)

In [22]:
datafusion.to_csv("DatasansHALE.csv",index=False, sep=';')

In [23]:
datafusion.groupby('Statut').describe()

           Années                                                            \
            count    mean       std     min     25%     50%     75%     max
Statut
Developed   286.0  2010.5  6.355409  2000.0  2005.0  2010.5  2016.0  2021.0
Developing  286.0  2010.5  6.355409  2000.0  2005.0  2010.5  2016.0  2021.0

           LE_hommes             ... Cancer_Testicule            VIH/SIDA  \
               count       mean  ...              75%        max    count
Statut                           ...
Developed      286.0  76.558259  ...        11.302507  41.649008    286.0
Developing     286.0  64.452797  ...        10.285778  39.821276    286.0

                                                                        \
                   mean          std       min         25%         50%
Statut
Developed    108.783679   156.209398  6.582477   28.956763   53.007767
Developing  3266.429336  6450.180181  5.416906  135.873292  371.598870


                    75%           max
Statut
Developed    125.881942    848.973505
Developing  2893.848390  33671.647667

[2 rows x 448 columns]

## Ajout de la variable HDI

In [24]:
data3 = pd.read_excel('hdr-data.xlsx')
data3.head()

,countryIsoCode,country,indexCode,index,dimension,indicatorCode,indicator,year,yearStr,actualValue,value,note
0,BRA,Brazil,HDI,Human Development Index,NaN,hdi,Human Development Index (value),2000,2000,0.690,0.690,NaN
1,BRA,Brazil,HDI,Human Development Index,NaN,hdi,Human Development Index (value),2001,2001,0.694,0.694,NaN
2,BRA,Brazil,HDI,Human Development Index,NaN,hdi,Human Development Index (value),2002,2002,0.700,0.700,NaN
3,BRA,Brazil,HDI,Human Development Index,NaN,hdi,Human Development Index (value),2003,2003,0.705,0.705,NaN
4,BRA,Brazil,HDI,Human Development Index,NaN,hdi,Human Development Index (value),2004,2004,0.712,0.712,NaN

In [25]:
data3 = data3.drop(columns=['dimension','yearStr','value','note'])
data3.head(10)

,countryIsoCode,country,indexCode,index,indicatorCode,indicator,year,actualValue
0,BRA,Brazil,HDI,Human Development Index,hdi,Human Development Index (value),2000,0.690
1,BRA,Brazil,HDI,Human Development Index,hdi,Human Development Index (value),2001,0.694
2,BRA,Brazil,HDI,Human Development Index,hdi,Human Development Index (value),2002,0.700
3,BRA,Brazil,HDI,Human Development Index,hdi,Human Development Index (value),2003,0.705
4,BRA,Brazil,HDI,Human Development Index,hdi,Human Development Index (value),2004,0.712
5,BRA,Brazil,HDI,Human Development Index,hdi,Human Development Index (value),2005,0.718
6,BRA,Brazil,HDI,Human Development Index,hdi,Human Development Index (value),2006,0.725
7,BRA,Brazil,HDI,Human Development Index,hdi,Human Development Index (value),2007,0.732
8,BRA,Brazil,HDI,Human Development Index,hdi,Human Development Index (value),2008,0.739
9,BRA,Brazil,HDI,Human Development Index,hdi,Human Development Index (value),2009,0.742

In [26]:
data3['indicator'].unique()

array(['Human Development Index (value)', 'HDI female', 'HDI male'],
      dtype=object)

In [27]:
data3['index'].unique()

array(['Human Development Index', 'Gender Development Index'],
      dtype=object)

In [28]:
# 
data3 = data3[data3["index"] == "Human Development Index"]

#
df3 = data3.pivot_table(
    index=["countryIsoCode", "country", "year"],
    values="actualValue"
).reset_index()


df3 = df3.rename(columns={
    "countryIsoCode": "Code_Pays",
    "country": "Pays",
    "year": "Années",
    "Human Development Index (value)": "IDH",
    'actualValue': "IDH"
})


dico_pays = {
    "South Africa": "Afrique du Sud",
    "Germany": "Allemagne",
    "Brazil": "Brésil",
    "Canada": "Canada",
    "Chile": "Chili",
    "Hong Kong, China (SAR)": "Chine",
    "Korea (Republic of)": "Corée du Sud",
    "Côte d'Ivoire": "Côte d'Ivoire",
    "Spain": "Espagne",
    "France": "France",
    "India": "Inde",
    "Indonesia": "Indonésie",
    "Iran (Islamic Republic of)": "Iran",
    "Japan": "Japon",
    "Morocco": "Maroc",
    "Mexico": "Mexique",
    "Nigeria": "Nigeria",
    "Peru": "Pérou",
    "United Kingdom": "Royaume-Uni",
    "Russian Federation": "Russie",
    "Switzerland": "Suisse",
    "Sweden": "Suède",
    "Senegal": "Sénégal",
    "Togo": "Togo",
    "Türkiye": "Turquie",
    "United States": "États-Unis"
}

df3["Pays"] = df3["Pays"].replace(dico_pays)
df3.head(50)

   Code_Pays    Pays  Années    IDH
0        BRA  Brésil    2000  0.690
1        BRA  Brésil    2001  0.694
2        BRA  Brésil    2002  0.700
3        BRA  Brésil    2003  0.705
4        BRA  Brésil    2004  0.712
5        BRA  Brésil    2005  0.718
6        BRA  Brésil    2006  0.725
7        BRA  Brésil    2007  0.732
8        BRA  Brésil    2008  0.739
9        BRA  Brésil    2009  0.742
10       BRA  Brésil    2010  0.748
11       BRA  Brésil    2011  0.753
12       BRA  Brésil    2012  0.758
13       BRA  Brésil    2013  0.762
14       BRA  Brésil    2014  0.765
15       BRA  Brésil    2015  0.764
16       BRA  Brésil    2016  0.765
17       BRA  Brésil    2017  0.770
18       BRA  Brésil    2018  0.774
19       BRA  Brésil    2019  0.776
20       BRA  Brésil    2020  0.770
21       BRA  Brésil    2021  0.768
22       CAN  Canada    2000  0.894
23       CAN  Canada    2001  0.897
24       CAN  Canada    2002  0.899
25       CAN  Canada    2003  0.902
26       CAN  Canada    2004  0.906
27       CAN  Canada    2005  0.909
28       CAN  Canada    2006  0.913
29       CAN  Canada    2007  0.914
30       CAN  Canada    2008  0.916
31       CAN  Canada    2009  0.915
32       CAN  Canada    2010  0.918
33       CAN  Canada    2011  0.921
34       CAN  Canada    2012  0.927
35       CAN  Canada    2013  0.930
36       CAN  Canada    2014  0.932
37       CAN  Canada    2015  0.932
38       CAN  Canada    2016  0.933
39       CAN  Canada    2017  0.935
40       CAN  Canada    2018  0.935
41       CAN  Canada    2019  0.937
42       CAN  Canada    2020  0.931
43       CAN  Canada    2021  0.937
44       CHE  Suisse    2000  0.892
45       CHE  Suisse    2001  0.895
46       CHE  Suisse    2002  0.896
47       CHE  Suisse    2003  0.901
48       CHE  Suisse    2004  0.906
49       CHE  Suisse    2005  0.909

In [29]:
df3.isnull().sum()

Code_Pays    0
Pays         0
Années       0
IDH          0
dtype: int64

In [30]:
df3.shape

(572, 4)

In [31]:
df3.columns

Index(['Code_Pays', 'Pays', 'Années', 'IDH'], dtype='object')

In [32]:
df3['Pays'].unique()

array(['Brésil', 'Canada', 'Suisse', 'Chili', "Côte d'Ivoire",
       'Allemagne', 'Espagne', 'France', 'Royaume-Uni', 'Chine',
       'Indonésie', 'Inde', 'Iran', 'Japon', 'Corée du Sud', 'Maroc',
       'Mexique', 'Nigeria', 'Pérou', 'Russie', 'Sénégal', 'Suède',
       'Togo', 'Turquie', 'États-Unis', 'Afrique du Sud'], dtype=object)

In [33]:
df3 = df3.sort_values(by=["Pays", "Années"])
df3 = df3.reset_index(drop=True)
df3["Pays"].unique()

array(['Afrique du Sud', 'Allemagne', 'Brésil', 'Canada', 'Chili',
       'Chine', 'Corée du Sud', "Côte d'Ivoire", 'Espagne', 'France',
       'Inde', 'Indonésie', 'Iran', 'Japon', 'Maroc', 'Mexique',
       'Nigeria', 'Pérou', 'Royaume-Uni', 'Russie', 'Suisse', 'Suède',
       'Sénégal', 'Togo', 'Turquie', 'États-Unis'], dtype=object)

In [34]:
df3.to_csv("DataIDH.csv",index=False, sep=';')

In [35]:
pays_developed = [
    "Allemagne", "Canada", "Suisse", "France", "Royaume-Uni",
    "États-Unis", "Suède", "Japon", "Corée du Sud", "Espagne",
    "Russie", "Chine", "Espagne"
]

df3["Statut"] = df3["Pays"].apply(
    lambda x: "Developed" if x in pays_developed else "Developing"
)

df3.head(50)

   Code_Pays            Pays  Années    IDH      Statut
0        ZAF  Afrique du Sud    2000  0.618  Developing
1        ZAF  Afrique du Sud    2001  0.613  Developing
2        ZAF  Afrique du Sud    2002  0.614  Developing
3        ZAF  Afrique du Sud    2003  0.610  Developing
4        ZAF  Afrique du Sud    2004  0.613  Developing
5        ZAF  Afrique du Sud    2005  0.616  Developing
6        ZAF  Afrique du Sud    2006  0.622  Developing
7        ZAF  Afrique du Sud    2007  0.632  Developing
8        ZAF  Afrique du Sud    2008  0.643  Developing
9        ZAF  Afrique du Sud    2009  0.657  Developing
10       ZAF  Afrique du Sud    2010  0.669  Developing
11       ZAF  Afrique du Sud    2011  0.683  Developing
12       ZAF  Afrique du Sud    2012  0.696  Developing
13       ZAF  Afrique du Sud    2013  0.705  Developing
14       ZAF  Afrique du Sud    2014  0.713  Developing
15       ZAF  Afrique du Sud    2015  0.722  Developing
16       ZAF  Afrique du Sud    2016  0.722  Developing
17       ZAF  Afrique du Sud    2017  0.726  Developing
18       ZAF  Afrique du Sud    2018  0.732  Developing
19       ZAF  Afrique du Sud    2019  0.742  Developing
20       ZAF  Afrique du Sud    2020  0.724  Developing
21       ZAF  Afrique du Sud    2021  0.721  Developing
22       DEU       Allemagne    2000  0.897   Developed
23       DEU       Allemagne    2001  0.904   Developed
24       DEU       Allemagne    2002  0.909   Developed
25       DEU       Allemagne    2003  0.914   Developed
26       DEU       Allemagne    2004  0.923   Developed
27       DEU       Allemagne    2005  0.923   Developed
28       DEU       Allemagne    2006  0.927   Developed
29       DEU       Allemagne    2007  0.931   Developed
30       DEU       Allemagne    2008  0.933   Developed
31       DEU       Allemagne    2009  0.933   Developed
32       DEU       Allemagne    2010  0.936   Developed
33       DEU       Allemagne    2011  0.942   Developed
34       DEU       Allemagne    2012  0.944   Developed
35       DEU       Allemagne    2013  0.945   Developed
36       DEU       Allemagne    2014  0.949   Developed
37       DEU       Allemagne    2015  0.948   Developed
38       DEU       Allemagne    2016  0.949   Developed
39       DEU       Allemagne    2017  0.951   Developed
40       DEU       Allemagne    2018  0.952   Developed
41       DEU       Allemagne    2019  0.957   Developed
42       DEU       Allemagne    2020  0.955   Developed
43       DEU       Allemagne    2021  0.958   Developed
44       BRA          Brésil    2000  0.690  Developing
45       BRA          Brésil    2001  0.694  Developing
46       BRA          Brésil    2002  0.700  Developing
47       BRA          Brésil    2003  0.705  Developing
48       BRA          Brésil    2004  0.712  Developing
49       BRA          Brésil    2005  0.718  Developing

In [36]:
df3.isna().sum()

Code_Pays    0
Pays         0
Années       0
IDH          0
Statut       0
dtype: int64

In [37]:
df3= df3[~df3["Années"].isin([2022, 2023])]
df3['Années'].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])

In [38]:
import os
os.getcwd()

'/Users/fofanamohamed/Desktop/Stage'

In [39]:
import os
os.listdir("/Users/fofanamohamed/Desktop/L3MIASHS/Stage")

['OSHINUBI_2022_archivage.pdf',
 'Collecte des données.R',
 'DATAAPI.spyder-py3.spydata',
 'Untitled1.ipynb',
 '.DS_Store',
 'DatagFinal.csv',
 'Untitled.ipynb',
 'Healthy life expertancy.csv',
 'Rapport_stage_ERK.pdf',
 'Demography WM gap final.docx',
 'Memoire OCHOA Jorge.pdf',
 'AJAs',
 'Developpcont_LE.csv',
 'Forecasting 12.09.25.pdf',
 'Demography WM gap final.pdf',
 'convention_126408_MOHAMED_FOFANA.pdf',
 'untitled.txt',
 '.spyder-py3.spydata',
 'BdAPI.csv',
 'Analyse des disparités entre les femmes et les hommes dans la vie mondiale et l.pdf',
 'DATAAPI.spydata',
 'Experience de vie en bonne santé des 8pays.csv',
 'Nettoyage de donnees.ipynb',
 'Scripts',
 'dataAPI.csv',
 'ma_nouvelle_basefusion.csv',
 '.ipynb_checkpoints',
 'Developpingcontr_LE.csv',
 'Healthy life expertancy1.csv',
 'cancer_AJA.csv',
 'donnees_fusionnees_avec_Senegal.csv',
 'Life expertancy.csv',
 'Experance de vie en bonne sante perou.csv',
 'DeveloppingCont_HALE.csv',
 'PolyFML.pdf',
 'DeveloppCont_HALE.csv',
 'Requetdonnées.ipynb',
 'doses_vaccin_FR_trie_par_annee_et_pays.csv',
 '~$mography WM gap final.docx']

In [40]:
import pandas as pd

df4= pd.read_csv('/Users/fofanamohamed/Desktop/Stage/BdAPI.csv')
df4.columns

Index(['Année', 'Pays', 'Code Pays',
       'Espérance de vie à la naissance, hommes (années)',
       'Espérance de vie à la naissance, femmes (années)',
       'Espérance de vie à la naissance à 60 ans, femmes (années)',
       'Espérance de vie à la naissance à 60 ans, hommes (années)',
       'Taux de mortalité infantile, filles (pour 1 000 naissances vivantes)',
       'Taux de mortalité infantile, garçons (pour 1 000 naissances vivantes)',
       'PIB par habitant ($ US courants)', 'Gini index',
       'Taux de mortalité, adultes, hommes (pour 1 000 hommes adultes)',
       'Taux de mortalité, adultes, femmes (pour 1 000 femmes adultes)',
       'Chômage, femmes (% de la population active féminine)',
       'Chômage, hommes (% de la population active masculine)',
       'Émissions de CO2 par habitant (tonnes)',
       'Taux de naissance, brut (pour 1 000 personnes)',
       'Population âgée de 15 à 64 ans, hommes',
       'Population âgée de 15 à 64 ans, femmes',
       'Dépenses de santé actuelles (% du PIB)',
       'Mortalité prématurée par maladies cardiovasculaires, cancer, diabète ou maladies respiratoires chroniques (femmes, 30-70 ans)',
       'Mortalité prématurée par maladies cardiovasculaires, cancer, diabète ou maladies respiratoires chroniques (hommes, 30-70 ans)',
       'Incidence du VIH (% de la population de 15 à 49 ans)',
       'Prévalence du VIH, total (% de la population âgée de 15 à 49 ans)',
       'Population âgée de 0 à 4 ans, filles (% de la population féminine)',
       'Population âgée de 0 à 4 ans, garçons (% de la population masculine)',
       'Population âgée de 5 à 9 ans, filles (% de la population féminine)',
       'Population âgée de 5 à 9 ans, garçons (% de la population masculine)',
       'Population âgée de 10 à 14 ans, filles (% de la population féminine)',
       'Population âgée de 10 à 14 ans, garçons (% de la population masculine)',
       'Population âgée de 15 à 19 ans, filles (% de la population féminine)',
       'Population âgée de 15 à 19 ans, garçons (% de la population masculine)',
       'Population âgée de 20 à 24 ans, femmes (% de la population féminine)',
       'Population âgée de 20 à 24 ans, hommes (% de la population masculine)',
       'Population âgée de 25 à 29 ans, femmes (% de la population féminine)',
       'Population âgée de 25 à 29 ans, hommes (% de la population masculine)',
       'Population âgée de 30 à 34 ans, femmes (% de la population féminine)',
       'Population âgée de 30 à 34 ans, hommes (% de la population masculine)',
       'Population âgée de 35 à 39 ans, femmes (% de la population féminine)',
       'Population âgée de 35 à 39 ans, hommes (% de la population masculine)',
       'Population âgée de 40 à 44 ans, femmes (% de la population féminine)',
       'Population âgée de 40 à 44 ans, hommes (% de la population masculine)',
       'Population âgée de 45 à 49 ans, femmes (% de la population féminine)',
       'Population âgée de 45 à 49 ans, hommes (% de la population masculine)',
       'Population âgée de 50 à 54 ans, femmes (% de la population féminine)',
       'Population âgée de 50 à 54 ans, hommes (% de la population masculine)',
       'Population âgée de 55 à 59 ans, femmes (% de la population féminine)',
       'Population âgée de 55 à 59 ans, hommes (% de la population masculine)',
       'Population âgée de 60 à 64 ans, femmes (% de la population féminine)',
       'Population âgée de 60 à 64 ans, hommes (% de la population masculine)',
       'Population âgée de 65 à 69 ans, femmes (% de la population féminine)',
       'Population âgée de 65 à 69 ans, hommes (% de la population masculine)',
       'Population âgée de 70 à 74 ans, femmes (% de la population féminine)',
       'Population âgée de 70 à 74 ans, hommes (% de la population masculine)',
       'Population âgée de 75 à 79 ans, femmes (% de la population féminine)',
       'Population âgée de 75 à 79 ans, hommes (% de la population masculine)',
       'Population âgée de 80 ans et plus, femmes (% de la population féminine)',
       'Population âgée de 80 ans et plus, hommes (% de la population masculine)'],
      dtype='object')

In [41]:
df4.rename(columns={'Année': 'Années','Code Pays': 'Code_Pays'}, inplace=True)
df4['Pays'].unique()

array(['Afrique du Sud', 'Allemagne', 'Brésil', 'Canada', 'Chine',
       'Chili', 'Corée du Sud', "Côte d'Ivoire", 'Espagne', 'France',
       'Inde', 'Indonésie', 'Iran', 'Japon', 'Maroc', 'Mexique',
       'Nigeria', 'Pérou', 'Royaume-Uni', 'Russie', 'Sénégal', 'Suède',
       'Suisse', 'Togo', 'Turquie', 'États-Unis'], dtype=object)

In [42]:
# Sélectionner seulement les colonnes utiles
cols_to_keep = [
    'Années',
    'Pays',
    'Code_Pays',
    "Chômage, femmes (% de la population active féminine)",
    "Chômage, hommes (% de la population active masculine)",
    "Mortalité prématurée par maladies cardiovasculaires, cancer, diabète ou maladies respiratoires chroniques (femmes, 30-70 ans)",
    "Mortalité prématurée par maladies cardiovasculaires, cancer, diabète ou maladies respiratoires chroniques (hommes, 30-70 ans)",
    "Émissions de CO2 par habitant (tonnes)"
]

df = df4[cols_to_keep]

df = df.rename(columns={
    "Chômage, femmes (% de la population active féminine)": "Chomage_femmes",
    "Chômage, hommes (% de la population active masculine)": "Chomage_hommes",
    "Mortalité prématurée par maladies cardiovasculaires, cancer, diabète ou maladies respiratoires chroniques (femmes, 30-70 ans)": "Mort_prem_F",
    "Mortalité prématurée par maladies cardiovasculaires, cancer, diabète ou maladies respiratoires chroniques (hommes, 30-70 ans)": "Mort_prem_H",
    "Émissions de CO2 par habitant (tonnes)": "CO2_habitant"
})
df.head()

,Années,Pays,Code_Pays,Chomage_femmes,Chomage_hommes,Mort_prem_F,Mort_prem_H,CO2_habitant
0,2000,Afrique du Sud,ZAF,26.044,19.934,17.7,26.9,7.364278
1,2000,Allemagne,DEU,8.271,7.641,11.2,21.1,10.603573
2,2000,Brésil,BRA,14.229,8.660,17.2,24.8,2.007819
3,2000,Canada,CAN,6.695,6.942,11.3,17.7,17.696982
4,2000,Chine,CHN,2.834,3.613,19.7,28.3,2.904182

In [43]:
df= df[~df["Années"].isin([2022, 2023])]
df['Années'].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])

In [44]:
df['Années'].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])

In [48]:
df_final = df.merge(df, on=["Pays", "Années"], how="left")
df_final.columns
df_final.head(30)

,Années,Pays,Code_Pays_x,Chomage_femmes_x,Chomage_hommes_x,Mort_prem_F_x,Mort_prem_H_x,CO2_habitant_x,Code_Pays_y,Chomage_femmes_y,Chomage_hommes_y,Mort_prem_F_y,Mort_prem_H_y,CO2_habitant_y
0,2000,Afrique du Sud,ZAF,26.044,19.934,17.7,26.9,7.364278,ZAF,26.044,19.934,17.7,26.9,7.364278
1,2000,Allemagne,DEU,8.271,7.641,11.2,21.1,10.603573,DEU,8.271,7.641,11.2,21.1,10.603573
2,2000,Brésil,BRA,14.229,8.660,17.2,24.8,2.007819,BRA,14.229,8.660,17.2,24.8,2.007819
3,2000,Canada,CAN,6.695,6.942,11.3,17.7,17.696982,CAN,6.695,6.942,11.3,17.7,17.696982
4,2000,Chine,CHN,2.834,3.613,19.7,28.3,2.904182,CHN,2.834,3.613,19.7,28.3,2.904182
5,2000,Chili,CHL,12.487,9.453,11.8,16.4,3.473482,CHL,12.487,9.453,11.8,16.4,3.473482
6,2000,Corée du Sud,KOR,3.231,4.623,10.9,23.1,10.086725,KOR,3.231,4.623,10.9,23.1,10.086725
7,2000,Côte d'Ivoire,CIV,4.895,4.767,16.2,26.5,0.393644,CIV,4.895,4.767,16.2,26.5,0.393644
8,2000,Espagne,ESP,20.367,9.497,8.2,19.3,7.721380,ESP,20.367,9.497,8.2,19.3,7.721380
9,2000,France,FRA,12.205,8.543,8.7,19.7,6.586015,FRA,12.205,8.543,8.7,19.7,6.586015
10,2000,Inde,IND,7.686,7.601,20.0,25.7,0.941139,IND,7.686,7.601,20.0,25.7,0.941139
11,2000,Indonésie,IDN,6.706,5.683,25.0,26.9,1.384188,IDN,6.706,5.683,25.0,26.9,1.384188
12,2000,Iran,IRN,19.380,10.313,15.6,22.0,5.328763,IRN,19.380,10.313,15.6,22.0,5.328763
13,2000,Japon,JPN,4.505,4.912,7.5,15.3,9.845295,JPN,4.505,4.912,7.5,15.3,9.845295
14,2000,Maroc,MAR,13.016,13.765,23.4,24.6,1.180593,MAR,13.016,13.765,23.4,24.6,1.180593
15,2000,Mexique,MEX,3.377,2.269,16.2,17.9,4.022424,MEX,3.377,2.269,16.2,17.9,4.022424
16,2000,Nigeria,NGA,3.868,4.048,19.2,22.7,0.793659,NGA,3.868,4.048,19.2,22.7,0.793659
17,2000,Pérou,PER,5.019,4.915,11.1,10.9,1.089696,PER,5.019,4.915,11.1,10.9,1.089696
18,2000,Royaume-Uni,GBR,4.863,6.141,13.0,20.0,9.367569,GBR,4.863,6.141,13.0,20.0,9.367569
19,2000,Russie,RUS,10.368,10.781,24.4,50.8,11.467802,RUS,10.368,10.781,24.4,50.8,11.467802
20,2000,Sénégal,SEN,2.901,2.550,23.1,26.1,0.400250,SEN,2.901,2.550,23.1,26.1,0.400250
21,2000,Suède,SWE,5.000,5.892,10.6,15.8,6.535334,SWE,5.000,5.892,10.6,15.8,6.535334
22,2000,Suisse,CHE,3.119,2.293,9.0,16.3,6.235849,CHE,3.119,2.293,9.0,16.3,6.235849
23,2000,Togo,TGO,4.110,4.233,25.2,31.4,0.243345,TGO,4.110,4.233,25.2,31.4,0.243345
24,2000,Turquie,TUR,6.269,6.577,15.6,29.6,3.470280,TUR,6.269,6.577,15.6,29.6,3.470280
25,2000,États-Unis,USA,4.101,3.903,14.6,21.0,21.012618,USA,4.101,3.903,14.6,21.0,21.012618
26,2001,Afrique du Sud,ZAF,25.899,19.819,17.5,26.4,7.513709,ZAF,25.899,19.819,17.5,26.4,7.513709
27,2001,Allemagne,DEU,7.780,7.768,10.8,20.2,10.756759,DEU,7.780,7.768,10.8,20.2,10.756759
28,2001,Brésil,BRA,13.774,8.499,16.7,24.3,1.992685,BRA,13.774,8.499,16.7,24.3,1.992685
29,2001,Canada,CAN,6.855,7.527,11.1,17.1,17.224209,CAN,6.855,7.527,11.1,17.1,17.224209

In [49]:
df_final.columns

Index(['Années', 'Pays', 'Code_Pays_x', 'Chomage_femmes_x', 'Chomage_hommes_x',
       'Mort_prem_F_x', 'Mort_prem_H_x', 'CO2_habitant_x', 'Code_Pays_y',
       'Chomage_femmes_y', 'Chomage_hommes_y', 'Mort_prem_F_y',
       'Mort_prem_H_y', 'CO2_habitant_y'],
      dtype='object')

In [54]:
print(set(df["Années"]) - set(df["Années"]))

set()

In [56]:
idx = df_final.columns.get_loc("VIH_SIDA") + 1
cols_to_move = df_final.columns[-5:].tolist()
for i, col in enumerate(cols_to_move):
    # Supprimer la colonne et récupérer les valeurs
    vals = df_final.pop(col)
    # Insérer après HID (idx+i pour avancer à chaque insertion)
    df_final.insert(loc=idx + i, column=col, value=vals)
df_final.columns

KeyError: 'VIH_SIDA'

In [57]:
df_final.head()

,Années,Pays,Code_Pays_x,Chomage_femmes_x,Chomage_hommes_x,Mort_prem_F_x,Mort_prem_H_x,CO2_habitant_x,Code_Pays_y,Chomage_femmes_y,Chomage_hommes_y,Mort_prem_F_y,Mort_prem_H_y,CO2_habitant_y
0,2000,Afrique du Sud,ZAF,26.044,19.934,17.7,26.9,7.364278,ZAF,26.044,19.934,17.7,26.9,7.364278
1,2000,Allemagne,DEU,8.271,7.641,11.2,21.1,10.603573,DEU,8.271,7.641,11.2,21.1,10.603573
2,2000,Brésil,BRA,14.229,8.660,17.2,24.8,2.007819,BRA,14.229,8.660,17.2,24.8,2.007819
3,2000,Canada,CAN,6.695,6.942,11.3,17.7,17.696982,CAN,6.695,6.942,11.3,17.7,17.696982
4,2000,Chine,CHN,2.834,3.613,19.7,28.3,2.904182,CHN,2.834,3.613,19.7,28.3,2.904182

In [58]:
print(set(df3["Pays"]) - set(df["Pays"]))
print(set(df3["Années"]) - set(df["Années"]))

set()
set()

In [59]:
print(df_final)

     Années            Pays Code_Pays_x  Chomage_femmes_x  Chomage_hommes_x  \
0      2000  Afrique du Sud         ZAF            26.044            19.934
1      2000       Allemagne         DEU             8.271             7.641
2      2000          Brésil         BRA            14.229             8.660
3      2000          Canada         CAN             6.695             6.942
4      2000           Chine         CHN             2.834             3.613
..      ...             ...         ...               ...               ...
567    2021           Suède         SWE             9.054             8.425
568    2021          Suisse         CHE             5.237             4.816
569    2021            Togo         TGO             2.301             2.363
570    2021         Turquie         TUR            14.715            10.671
571    2021      États-Unis         USA             5.210             5.463

     Mort_prem_F_x  Mort_prem_H_x  CO2_habitant_x Code_Pays_y  \
0             17.7           26.9        7.364278         ZAF
1             11.2           21.1       10.603573         DEU
2             17.2           24.8        2.007819         BRA
3             11.3           17.7       17.696982         CAN
4             19.7           28.3        2.904182         CHN
..             ...            ...             ...         ...
567            6.6            9.2        3.828871         SWE
568            5.7            9.3        4.317192         CHE
569           22.9           27.9        0.277078         TGO
570           10.1           20.7        5.474392         TUR
571           10.9           16.4       14.318540         USA

     Chomage_femmes_y  Chomage_hommes_y  Mort_prem_F_y  Mort_prem_H_y  \
0              26.044            19.934           17.7           26.9
1               8.271             7.641           11.2           21.1
2              14.229             8.660           17.2           24.8
3               6.695             6.942           11.3           17.7
4               2.834             3.613           19.7           28.3
..                ...               ...            ...            ...
567             9.054             8.425            6.6            9.2
568             5.237             4.816            5.7            9.3
569             2.301             2.363           22.9           27.9
570            14.715            10.671           10.1           20.7
571             5.210             5.463           10.9           16.4

     CO2_habitant_y
0          7.364278
1         10.603573
2          2.007819
3         17.696982
4          2.904182
..              ...
567        3.828871
568        4.317192
569        0.277078
570        5.474392
571       14.318540

[572 rows x 14 columns]

In [61]:
dt = pd.read_csv('DatagFinal.csv')
dt.head(30)

,Années,Pays,Code_Pays,Statut,HALE_femmes,HALE_hommes,LE_femmes,LE_hommes,LE_60_femmes,LE_60_hommes,...,Pop_60_64_femmes,Pop_60_64_hommes,Pop_65_69_femmes,Pop_65_69_hommes,Pop_70_74_femmes,Pop_70_74_hommes,Pop_75_79_femmes,Pop_75_79_hommes,Pop_80_plus_femmes,Pop_80_plus_hommes
0,2000,Brésil,BRA,Developing,62.737055,59.172181,72.960,66.347,19.4932,16.5902,...,2.719295,2.489838,2.271030,1.844012,1.713595,1.295986,1.046500,0.751321,0.822965,0.551714
1,2001,Brésil,BRA,Developing,62.963842,59.389943,73.400,66.699,19.6649,16.7358,...,2.744890,2.543488,2.277358,1.865670,1.751965,1.317702,1.092544,0.775602,0.855875,0.569281
2,2002,Brésil,BRA,Developing,63.091429,59.578401,73.843,67.085,19.8502,16.9187,...,2.776097,2.595700,2.285800,1.896928,1.785950,1.338731,1.139355,0.800088,0.893839,0.589901
3,2003,Brésil,BRA,Developing,63.265723,59.785036,74.337,67.558,20.1474,17.2464,...,2.812252,2.646808,2.299738,1.937946,1.814942,1.359915,1.186709,0.825261,0.937720,0.613985
4,2004,Brésil,BRA,Developing,63.375544,59.963533,74.824,68.019,20.4626,17.5307,...,2.854592,2.697717,2.322712,1.989437,1.839327,1.382518,1.233853,0.850931,0.987538,0.641215
5,2005,Brésil,BRA,Developing,63.798963,60.499426,75.292,68.485,20.7702,17.8210,...,2.906301,2.750505,2.352784,2.047107,1.860279,1.407819,1.279526,0.877025,1.042252,0.670606
6,2006,Brésil,BRA,Developing,63.975986,60.709837,75.744,68.953,21.0757,18.1165,...,2.974119,2.803063,2.387872,2.105945,1.881278,1.440012,1.323677,0.904205,1.101655,0.701907
7,2007,Brésil,BRA,Developing,64.286733,60.965815,76.191,69.368,21.3933,18.4133,...,3.064569,2.864956,2.428231,2.164559,1.904771,1.480770,1.366075,0.932389,1.166375,0.735822
8,2008,Brésil,BRA,Developing,64.543781,61.136095,76.585,69.733,21.6651,18.6702,...,3.179063,2.949663,2.473210,2.222657,1.933030,1.529358,1.405315,0.961179,1.236201,0.772563
9,2009,Brésil,BRA,Developing,64.754057,61.312744,76.930,70.076,21.9036,18.9100,...,3.322509,3.062065,2.523854,2.280856,1.968597,1.586185,1.440767,0.990820,1.310027,0.811696
10,2010,Brésil,BRA,Developing,64.908731,61.410904,77.257,70.392,22.1350,19.1538,...,3.485221,3.192620,2.582907,2.340895,2.009783,1.648273,1.473175,1.022476,1.386573,0.853189
11,2011,Brésil,BRA,Developing,64.989659,61.536016,77.532,70.654,22.3304,19.3547,...,3.647324,3.332591,2.655608,2.399751,2.054101,1.710864,1.504708,1.058921,1.465273,0.897343
12,2012,Brésil,BRA,Developing,65.254729,61.728416,77.816,70.945,22.5022,19.5346,...,3.801651,3.475801,2.747084,2.464630,2.100812,1.771681,1.536492,1.100874,1.545426,0.944032
13,2013,Brésil,BRA,Developing,65.417760,61.864239,78.062,71.246,22.6605,19.7111,...,3.946131,3.610694,2.858578,2.547115,2.149173,1.830060,1.570142,1.147769,1.625358,0.992772
14,2014,Brésil,BRA,Developing,65.624593,62.032085,78.273,71.462,22.7941,19.8197,...,4.074033,3.731641,2.994682,2.651702,2.200339,1.886235,1.607761,1.199682,1.703303,1.042695
15,2015,Brésil,BRA,Developing,65.650938,62.171937,78.472,71.818,22.8928,19.9763,...,4.193109,3.846992,3.147086,2.770667,2.257265,1.942222,1.648029,1.254362,1.778344,1.093697
16,2016,Brésil,BRA,Developing,65.593331,62.023522,78.539,71.716,22.9517,19.8433,...,4.314378,3.965378,3.298909,2.897011,2.325674,1.995435,1.689611,1.307850,1.852108,1.147293
17,2017,Brésil,BRA,Developing,65.897551,62.390006,78.781,72.069,23.0404,20.0293,...,4.436506,4.084504,3.445352,3.027808,2.411277,2.053320,1.732763,1.359014,1.925113,1.203989
18,2018,Brésil,BRA,Developing,66.064572,62.726181,78.977,72.365,23.1461,20.0207,...,4.561007,4.206131,3.585005,3.154294,2.516412,2.127522,1.777940,1.408122,1.997508,1.262774
19,2019,Brésil,BRA,Developing,66.074219,62.962178,79.023,72.653,23.1638,20.0079,...,4.686578,4.328883,3.710152,3.269484,2.645130,2.221591,1.826379,1.454987,2.069239,1.321518
20,2020,Brésil,BRA,Developing,64.964096,61.622737,77.599,71.537,21.9090,19.0707,...,4.809921,4.447542,3.825821,3.374575,2.786993,2.323220,1.877188,1.496909,2.108420,1.375315
21,2021,Brésil,BRA,Developing,63.405779,60.299787,76.401,69.810,21.6392,18.2314,...,4.925758,4.557133,3.938068,3.474989,2.922593,2.422519,1.933818,1.531229,2.145498,1.422817
22,2000,Canada,CAN,Developed,69.527418,67.473919,81.820,76.640,24.4753,20.5342,...,4.122787,4.024139,3.818222,3.608676,3.523557,3.013600,3.025100,2.193642,3.847110,2.008512
23,2001,Canada,CAN,Developed,69.639170,67.647121,82.000,76.920,24.6037,20.7959,...,4.196326,4.092650,3.774754,3.565698,3.511812,3.048083,3.028932,2.225209,3.970548,2.088581
24,2002,Canada,CAN,Developed,69.616435,67.781554,82.020,77.160,24.6286,20.9301,...,4.311488,4.207519,3.742998,3.528079,3.498060,3.072514,3.022273,2.255480,4.091428,2.172078
25,2003,Canada,CAN,Developed,69.740191,67.824043,82.230,77.320,24.7790,21.1041,...,4.460762,4.360940,3.739424,3.517563,3.477236,3.079757,3.012451,2.289685,4.207449,2.255095
26,2004,Canada,CAN,Developed,69.870181,68.037326,82.420,77.680,24.9605,21.3815,...,4.621457,4.527403,3.764514,3.538652,3.446794,3.069217,2.999504,2.323377,4.321365,2.340222
27,2005,Canada,CAN,Developed,69.909441,68.096972,82.520,77.820,25.0589,21.5869,...,4.783150,4.693726,3.811337,3.586636,3.413300,3.048022,2.989149,2.357612,4.429850,2.428259
28,2006,Canada,CAN,Developed,70.158290,68.416003,82.910,78.290,25.3784,21.9242,...,4.980717,4.893847,3.889895,3.669666,3.383358,3.025037,2.984625,2.393869,4.531809,2.517452
29,2007,Canada,CAN,Developed,70.148900,68.422992,82.910,78.290,25.3635,21.9491,...,5.224077,5.141644,4.001309,3.784910,3.362182,3.009284,2.980448,2.423301,4.619445,2.605662

In [63]:
dt.columns

Index(['Années', 'Pays', 'Code_Pays', 'Statut', 'HALE_femmes', 'HALE_hommes',
       'LE_femmes', 'LE_hommes', 'LE_60_femmes', 'LE_60_hommes', 'HALE_WMGap',
       'LE_WMGap', 'LE_WMGap_60', 'PIB_habitant', 'Dep_sante_PIB', 'Gini',
       'DPGS', 'IDH', 'Mort_adultes_hommes', 'Mort_adultes_femmes',
       'Mort_inf_filles', 'Mort_inf_garçons', 'VIH_SIDA', 'Cancer_Testicule',
       'Cancer_thyroïde', 'Cancer_Estomac', 'Cancer_Utérus', 'Cancer_Foie',
       'Cancer_Sein', 'Pop_0_4_filles', 'Pop_0_4_garçons', 'Pop_5_9_filles',
       'Pop_5_9_garçons', 'Pop_10_14_filles', 'Pop_10_14_garçons',
       'Pop_15_19_filles', 'Pop_15_19_garçons', 'Pop_20_24_femmes',
       'Pop_20_24_hommes', 'Pop_25_29_femmes', 'Pop_25_29_hommes',
       'Pop_30_34_femmes', 'Pop_30_34_hommes', 'Pop_35_39_femmes',
       'Pop_35_39_hommes', 'Pop_40_44_femmes', 'Pop_40_44_hommes',
       'Pop_45_49_femmes', 'Pop_45_49_hommes', 'Pop_50_54_femmes',
       'Pop_50_54_hommes', 'Pop_55_59_femmes', 'Pop_55_59_hommes',
       'Pop_60_64_femmes', 'Pop_60_64_hommes', 'Pop_65_69_femmes',
       'Pop_65_69_hommes', 'Pop_70_74_femmes', 'Pop_70_74_hommes',
       'Pop_75_79_femmes', 'Pop_75_79_hommes', 'Pop_80_plus_femmes',
       'Pop_80_plus_hommes'],
      dtype='object')

In [296]:
dt['IDH'].isna().sum()

np.int64(44)

In [131]:
df_final.to_csv("DataML.csv",index=False, sep=';')

In [109]:
col_after = "VIH_SIDA"
idx = df1.columns.get_loc(col_after) + 1

for i, col in enumerate(df.columns):
    if col not in df1.columns:
        df1.insert(loc=idx + i, column=col, value=df[col])
df1.columns

Index(['Années', 'Pays', 'Code_Pays', 'Statut', 'HALE_femmes', 'HALE_hommes',
       'LE_femmes', 'LE_hommes', 'LE_60_femmes', 'LE_60_hommes', 'HALE_WMGap',
       'LE_WMGap', 'LE_WMGap_60', 'PIB_habitant', 'Dep_sante_PIB', 'Gini',
       'DPGS', 'IDH', 'Mort_adultes_hommes', 'Mort_adultes_femmes',
       'Mort_inf_filles', 'Mort_inf_garçons', 'VIH_SIDA', 'Chomage_femmes',
       'Chomage_hommes', 'Mort_prem_F', 'Mort_prem_H', 'CO2_habitant',
       'Cancer_Testicule', 'Cancer_thyroïde', 'Cancer_Estomac',
       'Cancer_Utérus', 'Cancer_Foie', 'Cancer_Sein', 'Pop_0_4_filles',
       'Pop_0_4_garçons', 'Pop_5_9_filles', 'Pop_5_9_garçons',
       'Pop_10_14_filles', 'Pop_10_14_garçons', 'Pop_15_19_filles',
       'Pop_15_19_garçons', 'Pop_20_24_femmes', 'Pop_20_24_hommes',
       'Pop_25_29_femmes', 'Pop_25_29_hommes', 'Pop_30_34_femmes',
       'Pop_30_34_hommes', 'Pop_35_39_femmes', 'Pop_35_39_hommes',
       'Pop_40_44_femmes', 'Pop_40_44_hommes', 'Pop_45_49_femmes',
       'Pop_45_49_hommes', 'Pop_50_54_femmes', 'Pop_50_54_hommes',
       'Pop_55_59_femmes', 'Pop_55_59_hommes', 'Pop_60_64_femmes',
       'Pop_60_64_hommes', 'Pop_65_69_femmes', 'Pop_65_69_hommes',
       'Pop_70_74_femmes', 'Pop_70_74_hommes', 'Pop_75_79_femmes',
       'Pop_75_79_hommes', 'Pop_80_plus_femmes', 'Pop_80_plus_hommes'],
      dtype='object')

In [110]:
df1.head()

,Années,Pays,Code_Pays,Statut,HALE_femmes,HALE_hommes,LE_femmes,LE_hommes,LE_60_femmes,LE_60_hommes,...,Pop_60_64_femmes,Pop_60_64_hommes,Pop_65_69_femmes,Pop_65_69_hommes,Pop_70_74_femmes,Pop_70_74_hommes,Pop_75_79_femmes,Pop_75_79_hommes,Pop_80_plus_femmes,Pop_80_plus_hommes
0,2000,Brésil,BRA,Developing,62.737055,59.172181,72.960,66.347,19.4932,16.5902,...,2.719295,2.489838,2.271030,1.844012,1.713595,1.295986,1.046500,0.751321,0.822965,0.551714
1,2001,Brésil,BRA,Developing,62.963842,59.389943,73.400,66.699,19.6649,16.7358,...,2.744890,2.543488,2.277358,1.865670,1.751965,1.317702,1.092544,0.775602,0.855875,0.569281
2,2002,Brésil,BRA,Developing,63.091429,59.578401,73.843,67.085,19.8502,16.9187,...,2.776097,2.595700,2.285800,1.896928,1.785950,1.338731,1.139355,0.800088,0.893839,0.589901
3,2003,Brésil,BRA,Developing,63.265723,59.785036,74.337,67.558,20.1474,17.2464,...,2.812252,2.646808,2.299738,1.937946,1.814942,1.359915,1.186709,0.825261,0.937720,0.613985
4,2004,Brésil,BRA,Developing,63.375544,59.963533,74.824,68.019,20.4626,17.5307,...,2.854592,2.697717,2.322712,1.989437,1.839327,1.382518,1.233853,0.850931,0.987538,0.641215

In [114]:
df1.to_csv("DataML.csv",index=False, sep=';')

Années                0
Pays                  0
Code_Pays             0
Statut                0
HALE_femmes           0
                     ..
Pop_70_74_hommes      0
Pop_75_79_femmes      0
Pop_75_79_hommes      0
Pop_80_plus_femmes    0
Pop_80_plus_hommes    0
Length: 68, dtype: int64

In [285]:
df1['IDH'].isna().sum()

np.int64(44)

In [65]:
d = pd.read_csv('Dataglobal.csv')
d['IDH'].isnull().sum()

np.int64(0)

In [66]:
d.head()

,Pays,Années,HALE_femmes,HALE_hommes,HALE_WMGap,Code_Pays.x,Statut,LE_hommes,LE_femmes,LE_60_femmes,...,Cancer_Foie,Cancer_Sein,Cancer_Testicule,VIH_SIDA,LE_WMGap_calc,LE_WMGap60_calc,log_PIB,log_Gini,Code_Pays.y,IDH
0,Brésil,2000,62.737055,59.172181,3.564874,BRA,Developing,66.347,72.960,19.4932,...,30.561424,217.635615,7.718421,453.533734,6.613,2.9030,8.233914,3.977811,BRA,0.690
1,Brésil,2001,62.963842,59.389943,3.573899,BRA,Developing,66.699,73.400,19.6649,...,32.350675,220.721431,7.995392,447.912242,6.701,2.9291,8.063469,4.067316,BRA,0.694
2,Brésil,2002,63.091429,59.578401,3.513029,BRA,Developing,67.085,73.843,19.8502,...,33.813585,223.918612,8.261517,444.219065,6.758,2.9315,7.957156,4.062166,BRA,0.700
3,Brésil,2003,63.265723,59.785036,3.480686,BRA,Developing,67.558,74.337,20.1474,...,35.138358,225.974202,8.718587,438.208028,6.779,2.9010,8.036123,4.053523,BRA,0.705
4,Brésil,2004,63.375544,59.963533,3.412011,BRA,Developing,68.019,74.824,20.4626,...,36.689277,230.080862,8.550051,429.975297,6.805,2.9319,8.206262,4.034241,BRA,0.712

In [67]:
d.columns

Index(['Pays', 'Années', 'HALE_femmes', 'HALE_hommes', 'HALE_WMGap',
       'Code_Pays.x', 'Statut', 'LE_hommes', 'LE_femmes', 'LE_60_femmes',
       'LE_60_hommes', 'Mort_inf_filles', 'Mort_inf_garçons', 'PIB_habitant',
       'Gini', 'Mort_adultes_hommes', 'Mort_adultes_femmes', 'Dep_sante_PIB',
       'Pop_0_4_filles', 'Pop_0_4_garçons', 'Pop_5_9_filles',
       'Pop_5_9_garçons', 'Pop_10_14_filles', 'Pop_10_14_garçons',
       'Pop_15_19_filles', 'Pop_15_19_garçons', 'Pop_20_24_femmes',
       'Pop_20_24_hommes', 'Pop_25_29_femmes', 'Pop_25_29_hommes',
       'Pop_30_34_femmes', 'Pop_30_34_hommes', 'Pop_35_39_femmes',
       'Pop_35_39_hommes', 'Pop_40_44_femmes', 'Pop_40_44_hommes',
       'Pop_45_49_femmes', 'Pop_45_49_hommes', 'Pop_50_54_femmes',
       'Pop_50_54_hommes', 'Pop_55_59_femmes', 'Pop_55_59_hommes',
       'Pop_60_64_femmes', 'Pop_60_64_hommes', 'Pop_65_69_femmes',
       'Pop_65_69_hommes', 'Pop_70_74_femmes', 'Pop_70_74_hommes',
       'Pop_75_79_femmes', 'Pop_75_79_hommes', 'Pop_80_plus_femmes',
       'Pop_80_plus_hommes', 'LE_WMGap', 'LE_WMGap_60', 'DPGS',
       'Cancer_thyroïde', 'Cancer_Estomac', 'Cancer_Utérus', 'Cancer_Foie',
       'Cancer_Sein', 'Cancer_Testicule', 'VIH_SIDA', 'LE_WMGap_calc',
       'LE_WMGap60_calc', 'log_PIB', 'log_Gini', 'Code_Pays.y', 'IDH'],
      dtype='object')

In [68]:
df.columns

Index(['Années', 'Pays', 'Code_Pays', 'Chomage_femmes', 'Chomage_hommes',
       'Mort_prem_F', 'Mort_prem_H', 'CO2_habitant'],
      dtype='object')

In [69]:
d["Années"].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])

In [70]:
dfg = d.merge(df, on=["Pays", "Années"], how="left")
dfg.head()

,Pays,Années,HALE_femmes,HALE_hommes,HALE_WMGap,Code_Pays.x,Statut,LE_hommes,LE_femmes,LE_60_femmes,...,log_PIB,log_Gini,Code_Pays.y,IDH,Code_Pays,Chomage_femmes,Chomage_hommes,Mort_prem_F,Mort_prem_H,CO2_habitant
0,Brésil,2000,62.737055,59.172181,3.564874,BRA,Developing,66.347,72.960,19.4932,...,8.233914,3.977811,BRA,0.690,BRA,14.229,8.660,17.2,24.8,2.007819
1,Brésil,2001,62.963842,59.389943,3.573899,BRA,Developing,66.699,73.400,19.6649,...,8.063469,4.067316,BRA,0.694,BRA,13.774,8.499,16.7,24.3,1.992685
2,Brésil,2002,63.091429,59.578401,3.513029,BRA,Developing,67.085,73.843,19.8502,...,7.957156,4.062166,BRA,0.700,BRA,13.705,8.475,16.4,23.7,1.968645
3,Brésil,2003,63.265723,59.785036,3.480686,BRA,Developing,67.558,74.337,20.1474,...,8.036123,4.053523,BRA,0.705,BRA,14.280,8.948,16.1,23.5,1.918139
4,Brésil,2004,63.375544,59.963533,3.412011,BRA,Developing,68.019,74.824,20.4626,...,8.206262,4.034241,BRA,0.712,BRA,13.357,7.691,16.1,23.3,1.999386

In [71]:
dfg['IDH'].isnull().sum()

np.int64(0)

In [72]:
dfg.shape

(572, 74)

In [73]:
dfg.columns

Index(['Pays', 'Années', 'HALE_femmes', 'HALE_hommes', 'HALE_WMGap',
       'Code_Pays.x', 'Statut', 'LE_hommes', 'LE_femmes', 'LE_60_femmes',
       'LE_60_hommes', 'Mort_inf_filles', 'Mort_inf_garçons', 'PIB_habitant',
       'Gini', 'Mort_adultes_hommes', 'Mort_adultes_femmes', 'Dep_sante_PIB',
       'Pop_0_4_filles', 'Pop_0_4_garçons', 'Pop_5_9_filles',
       'Pop_5_9_garçons', 'Pop_10_14_filles', 'Pop_10_14_garçons',
       'Pop_15_19_filles', 'Pop_15_19_garçons', 'Pop_20_24_femmes',
       'Pop_20_24_hommes', 'Pop_25_29_femmes', 'Pop_25_29_hommes',
       'Pop_30_34_femmes', 'Pop_30_34_hommes', 'Pop_35_39_femmes',
       'Pop_35_39_hommes', 'Pop_40_44_femmes', 'Pop_40_44_hommes',
       'Pop_45_49_femmes', 'Pop_45_49_hommes', 'Pop_50_54_femmes',
       'Pop_50_54_hommes', 'Pop_55_59_femmes', 'Pop_55_59_hommes',
       'Pop_60_64_femmes', 'Pop_60_64_hommes', 'Pop_65_69_femmes',
       'Pop_65_69_hommes', 'Pop_70_74_femmes', 'Pop_70_74_hommes',
       'Pop_75_79_femmes', 'Pop_75_79_hommes', 'Pop_80_plus_femmes',
       'Pop_80_plus_hommes', 'LE_WMGap', 'LE_WMGap_60', 'DPGS',
       'Cancer_thyroïde', 'Cancer_Estomac', 'Cancer_Utérus', 'Cancer_Foie',
       'Cancer_Sein', 'Cancer_Testicule', 'VIH_SIDA', 'LE_WMGap_calc',
       'LE_WMGap60_calc', 'log_PIB', 'log_Gini', 'Code_Pays.y', 'IDH',
       'Code_Pays', 'Chomage_femmes', 'Chomage_hommes', 'Mort_prem_F',
       'Mort_prem_H', 'CO2_habitant'],
      dtype='object')

In [74]:
print(dfg['Code_Pays.y'])

0      BRA
1      BRA
2      BRA
3      BRA
4      BRA
      ...
567    USA
568    USA
569    USA
570    USA
571    USA
Name: Code_Pays.y, Length: 572, dtype: object

In [75]:
dfg = dfg.drop(columns=[
   'LE_WMGap_calc',
       'LE_WMGap60_calc', 'log_PIB', 'log_Gini', 'Code_Pays.y' 
])

In [76]:
dfg.shape

(572, 69)

In [77]:
cols_order = ["Années", "Pays", "Code_Pays.x", 'Statut', 'LE_femmes', 'LE_hommes', 'HALE_femmes', 
              'HALE_hommes', 'LE_60_femmes', 'LE_60_hommes', 'LE_WMGap', 'LE_WMGap_60', 'HALE_WMGap', 
             'PIB_habitant', 'Dep_sante_PIB', 'Gini','DPGS', 'IDH','Mort_adultes_hommes', 'Mort_adultes_femmes',
             'Mort_inf_filles', 'Mort_inf_garçons', 'Mort_prem_F', 'Mort_prem_H', 'Chomage_femmes', 'Chomage_hommes',
             'CO2_habitant', 'VIH_SIDA', 'Cancer_thyroïde', 'Cancer_Estomac', 'Cancer_Utérus', 'Cancer_Foie',
             'Cancer_Sein', 'Cancer_Testicule', 'Pop_0_4_filles', 'Pop_0_4_garçons', 'Pop_5_9_filles',
             'Pop_5_9_garçons', 'Pop_10_14_filles', 'Pop_10_14_garçons',
            'Pop_15_19_filles', 'Pop_15_19_garçons', 'Pop_20_24_femmes',
           'Pop_20_24_hommes', 'Pop_25_29_femmes', 'Pop_25_29_hommes',
       'Pop_30_34_femmes', 'Pop_30_34_hommes', 'Pop_35_39_femmes',
       'Pop_35_39_hommes', 'Pop_40_44_femmes', 'Pop_40_44_hommes',
       'Pop_45_49_femmes', 'Pop_45_49_hommes', 'Pop_50_54_femmes',
       'Pop_50_54_hommes', 'Pop_55_59_femmes', 'Pop_55_59_hommes',
       'Pop_60_64_femmes', 'Pop_60_64_hommes', 'Pop_65_69_femmes',
       'Pop_65_69_hommes', 'Pop_70_74_femmes', 'Pop_70_74_hommes',
       'Pop_75_79_femmes', 'Pop_75_79_hommes', 'Pop_80_plus_femmes',
       'Pop_80_plus_hommes',]
dfg = dfg[cols_order]

In [78]:
dfg.head()

,Années,Pays,Code_Pays.x,Statut,LE_femmes,LE_hommes,HALE_femmes,HALE_hommes,LE_60_femmes,LE_60_hommes,...,Pop_60_64_femmes,Pop_60_64_hommes,Pop_65_69_femmes,Pop_65_69_hommes,Pop_70_74_femmes,Pop_70_74_hommes,Pop_75_79_femmes,Pop_75_79_hommes,Pop_80_plus_femmes,Pop_80_plus_hommes
0,2000,Brésil,BRA,Developing,72.960,66.347,62.737055,59.172181,19.4932,16.5902,...,2.719295,2.489838,2.271030,1.844012,1.713595,1.295986,1.046500,0.751321,0.822965,0.551714
1,2001,Brésil,BRA,Developing,73.400,66.699,62.963842,59.389943,19.6649,16.7358,...,2.744890,2.543488,2.277358,1.865670,1.751965,1.317702,1.092544,0.775602,0.855875,0.569281
2,2002,Brésil,BRA,Developing,73.843,67.085,63.091429,59.578401,19.8502,16.9187,...,2.776097,2.595700,2.285800,1.896928,1.785950,1.338731,1.139355,0.800088,0.893839,0.589901
3,2003,Brésil,BRA,Developing,74.337,67.558,63.265723,59.785036,20.1474,17.2464,...,2.812252,2.646808,2.299738,1.937946,1.814942,1.359915,1.186709,0.825261,0.937720,0.613985
4,2004,Brésil,BRA,Developing,74.824,68.019,63.375544,59.963533,20.4626,17.5307,...,2.854592,2.697717,2.322712,1.989437,1.839327,1.382518,1.233853,0.850931,0.987538,0.641215

In [79]:
dfg.columns

Index(['Années', 'Pays', 'Code_Pays.x', 'Statut', 'LE_femmes', 'LE_hommes',
       'HALE_femmes', 'HALE_hommes', 'LE_60_femmes', 'LE_60_hommes',
       'LE_WMGap', 'LE_WMGap_60', 'HALE_WMGap', 'PIB_habitant',
       'Dep_sante_PIB', 'Gini', 'DPGS', 'IDH', 'Mort_adultes_hommes',
       'Mort_adultes_femmes', 'Mort_inf_filles', 'Mort_inf_garçons',
       'Mort_prem_F', 'Mort_prem_H', 'Chomage_femmes', 'Chomage_hommes',
       'CO2_habitant', 'VIH_SIDA', 'Cancer_thyroïde', 'Cancer_Estomac',
       'Cancer_Utérus', 'Cancer_Foie', 'Cancer_Sein', 'Cancer_Testicule',
       'Pop_0_4_filles', 'Pop_0_4_garçons', 'Pop_5_9_filles',
       'Pop_5_9_garçons', 'Pop_10_14_filles', 'Pop_10_14_garçons',
       'Pop_15_19_filles', 'Pop_15_19_garçons', 'Pop_20_24_femmes',
       'Pop_20_24_hommes', 'Pop_25_29_femmes', 'Pop_25_29_hommes',
       'Pop_30_34_femmes', 'Pop_30_34_hommes', 'Pop_35_39_femmes',
       'Pop_35_39_hommes', 'Pop_40_44_femmes', 'Pop_40_44_hommes',
       'Pop_45_49_femmes', 'Pop_45_49_hommes', 'Pop_50_54_femmes',
       'Pop_50_54_hommes', 'Pop_55_59_femmes', 'Pop_55_59_hommes',
       'Pop_60_64_femmes', 'Pop_60_64_hommes', 'Pop_65_69_femmes',
       'Pop_65_69_hommes', 'Pop_70_74_femmes', 'Pop_70_74_hommes',
       'Pop_75_79_femmes', 'Pop_75_79_hommes', 'Pop_80_plus_femmes',
       'Pop_80_plus_hommes'],
      dtype='object')

In [80]:
dfg.rename(columns={"Code_Pays.x": "Code_Pays"}, inplace=True)

In [81]:
dfg.columns

Index(['Années', 'Pays', 'Code_Pays', 'Statut', 'LE_femmes', 'LE_hommes',
       'HALE_femmes', 'HALE_hommes', 'LE_60_femmes', 'LE_60_hommes',
       'LE_WMGap', 'LE_WMGap_60', 'HALE_WMGap', 'PIB_habitant',
       'Dep_sante_PIB', 'Gini', 'DPGS', 'IDH', 'Mort_adultes_hommes',
       'Mort_adultes_femmes', 'Mort_inf_filles', 'Mort_inf_garçons',
       'Mort_prem_F', 'Mort_prem_H', 'Chomage_femmes', 'Chomage_hommes',
       'CO2_habitant', 'VIH_SIDA', 'Cancer_thyroïde', 'Cancer_Estomac',
       'Cancer_Utérus', 'Cancer_Foie', 'Cancer_Sein', 'Cancer_Testicule',
       'Pop_0_4_filles', 'Pop_0_4_garçons', 'Pop_5_9_filles',
       'Pop_5_9_garçons', 'Pop_10_14_filles', 'Pop_10_14_garçons',
       'Pop_15_19_filles', 'Pop_15_19_garçons', 'Pop_20_24_femmes',
       'Pop_20_24_hommes', 'Pop_25_29_femmes', 'Pop_25_29_hommes',
       'Pop_30_34_femmes', 'Pop_30_34_hommes', 'Pop_35_39_femmes',
       'Pop_35_39_hommes', 'Pop_40_44_femmes', 'Pop_40_44_hommes',
       'Pop_45_49_femmes', 'Pop_45_49_hommes', 'Pop_50_54_femmes',
       'Pop_50_54_hommes', 'Pop_55_59_femmes', 'Pop_55_59_hommes',
       'Pop_60_64_femmes', 'Pop_60_64_hommes', 'Pop_65_69_femmes',
       'Pop_65_69_hommes', 'Pop_70_74_femmes', 'Pop_70_74_hommes',
       'Pop_75_79_femmes', 'Pop_75_79_hommes', 'Pop_80_plus_femmes',
       'Pop_80_plus_hommes'],
      dtype='object')

In [82]:
dfg.to_csv("DataML.csv",index=False, sep=';')